name: validate-pr-source-branch

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  validate-pr-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ '${{ github.head_ref }}' != "develop" ]]; then
            echo "Error: Pull requests to 'main' can only come from 'develop'."
            exit 1
          fi
